# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brz < Formula
  desc "Browser automation CLI for humans and LLM agents"
  homepage "https://github.com/crackfetch/brainstorm"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.2.0/brainstorm_0.2.0_darwin_amd64.tar.gz"
      sha256 "85b12370a40bd4d9fd171121e2fafd88ebe82036c04f9c21151f5c91323e275c"

      define_method(:install) do
        bin.install "brz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.2.0/brainstorm_0.2.0_darwin_arm64.tar.gz"
      sha256 "3681c180e8d112dcaa0934cbb68ded3ad91f281232292433ad37011a68e96f06"

      define_method(:install) do
        bin.install "brz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.2.0/brainstorm_0.2.0_linux_amd64.tar.gz"
      sha256 "d87c6173c31f4a8669d1d658480494b49710236423d0549f82d8ea1051628efe"
      define_method(:install) do
        bin.install "brz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.2.0/brainstorm_0.2.0_linux_arm64.tar.gz"
      sha256 "bea74a16101c5d669be41016f7d657b8e90cbc17c354b165735bf5bdc2e409f0"
      define_method(:install) do
        bin.install "brz"
      end
    end
  end
end
