# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brz < Formula
  desc "Browser automation CLI for humans and LLM agents"
  homepage "https://github.com/crackfetch/brainstorm"
  version "0.11.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.11.3/brainstorm_0.11.3_darwin_amd64.tar.gz"
      sha256 "8c4a2d694594a510b25130b3b35ba000f125b49b65368d892fca5e6370462644"

      define_method(:install) do
        bin.install "brz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.11.3/brainstorm_0.11.3_darwin_arm64.tar.gz"
      sha256 "63f8887a556895d5568beddd1979a192e8bb3f295d8c67dd940c5f8ddbe934c5"

      define_method(:install) do
        bin.install "brz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.11.3/brainstorm_0.11.3_linux_amd64.tar.gz"
      sha256 "5de2f8c794b31a351650b5ebc79a73f63973d3b71fa6cae2e7ce1e76f08ae0bb"
      define_method(:install) do
        bin.install "brz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.11.3/brainstorm_0.11.3_linux_arm64.tar.gz"
      sha256 "013fd6c81d2f2b7906c55d0654f52ad859de49a54baa315ae51009d2b1ee710a"
      define_method(:install) do
        bin.install "brz"
      end
    end
  end
end
