# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brz < Formula
  desc "Browser automation CLI for humans and LLM agents"
  homepage "https://github.com/crackfetch/brainstorm"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.10.1/brainstorm_0.10.1_darwin_amd64.tar.gz"
      sha256 "91418703518da88706ad3f9469e61de56736dfd750a89d9548e332db3379a4d0"

      define_method(:install) do
        bin.install "brz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.10.1/brainstorm_0.10.1_darwin_arm64.tar.gz"
      sha256 "2833434ef001528fdcc891cccc2468f78bdeddef0865a4497f67847a6cee9c28"

      define_method(:install) do
        bin.install "brz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.10.1/brainstorm_0.10.1_linux_amd64.tar.gz"
      sha256 "00d24cbcc938e78c5dfdf6c1bd58523c7cb69c428e568a1dc1504e7f40b8fdbc"
      define_method(:install) do
        bin.install "brz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crackfetch/brainstorm/releases/download/v0.10.1/brainstorm_0.10.1_linux_arm64.tar.gz"
      sha256 "8828e0e185d00cef1b19b9bccd40972277e0c3977f0748abf3b883f873f77a0c"
      define_method(:install) do
        bin.install "brz"
      end
    end
  end
end
